@startuml
abstract class entity.student.StudentAbstract implements entity.student.Student {
- String name
- String country
- LodgingService home
- Service location
- void setHome(LodgingService)
}

class app.BoundsClass extends app.Bounds {
- String name
- Position topPosition
- Position bottomPosition
~ StudentStorage students
~ ServiceStorage services
}


class entity.service.LeisureService extends entity.service.ServiceAbstract {
}


interface app.CampusApp {
}

class entity.student.BookishStudent extends entity.student.StudentAbstract  {
# List<Service> visited
}


class entity.student.ThriftyStudent extends entity.student.StudentAbstract {
~ EatingService cheapestEating
}

interface entity.student.Student {
}

class entity.student.OutgoingStudent extends entity.student.StudentAbstract {
# SinglyLinkedList<Service> visited
}


interface entity.service.StudentStoringService extends entity.service.Service {
~ void addUser(Student)
~ void removeUser(Student)
~ TwoWayIterator<Student> getUsers()
}

class entity.service.LodgingService extends entity.service.AbstractStudentStoringService {
}

class app.StudentStorage {
# SepChainHashTable<String, Student> studentsByName
# SepChainHashTable<String, SinglyLinkedList<Student>> studentsByCountry
# AVLSortedMap<String, Student> alphabeticalStudents
+ void addStudent(Student)
+ Student getStudent(String)
+ Student removeStudent(Student)
+ Iterator<Student> getAllStudents()
+ Iterator<Student> getStudentsByCountry(String)
- void readObject(ObjectInputStream)
}


interface app.Bounds {
}

class app.ServiceStorage {
# SinglyLinkedList<Service> services
# SepChainHashTable<String, Service> servicesByName
# ObjectRemovalSinglyList<Service>[5] servicesByStar
+ void addService(Service)
+ void updateServiceRating(Service, int old)
+ Service getService(String)
+ Iterator<Service> listAllServices()
~ Iterator<Service> listServicesByRanking()
- void readObject(ObjectInputStream)
}

abstract class entity.service.ServiceAbstract implements entity.service.Service {
- String name
- Position position
- int price
- int value
~ int rating
~ SepChainHashTable<String> tags
# int getValue()
}

class entity.service.EatingService extends entity.service.AbstractStudentStoringService {
}

class app.CampusAppClass extends app.CampusApp {
~ Bounds currentBounds
}

record app.Position {
+ long longitude()
+ long latitude()
+ long getManhattanDistance(Position)
}


abstract class entity.service.AbstractStudentStoringService extends entity.service.ServiceAbstract implements entity.service.StudentStoringService {
- DoublyLinkedList<Student> users
}

interface entity.service.Service {
}

app.BoundsClass ..> app.ServiceStorage : Use
app.BoundsClass ..> app.StudentStorage : Use
@enduml